# Generated by Django 4.0.2 on 2022-03-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_tag_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='tags_pro', to='shows.Tag'),
        ),
    ]
